Added types for db requests
Little-Pie/pie-server pull request #9
Opened 2022-11-25 10:20 UTC by Little-Pie

https://github.com/Little-Pie/pie-server/issues/2

2022-11-28 03:56 UTC, pavelzarubin requested changes

2022-11-28 03:56 UTC, pavelzarubin commented on src/Types/Db.hs
> +  }
У тебя же все эти сущности парсятся из запроса, почему бы их не пробросить, а не создавать новые. К тому же это нужно сделать везде. А еще можно добавить ToRow.

2022-12-01 07:31 UTC, Little-Pie commented
Там у меня не для всех получилось сделать типы из API, они отличаются. И для create/edit post не подходит ToRow

2022-12-02 04:13 UTC, pavelzarubin approved these changes

2022-12-02 09:19 UTC, merged